site_name: "Dynatrace Observability Lab: Predictive Auto-Scaling for Kubernetes Workloads"
repo_name: "GitHub"
repo_url: "https://github.com/dynatrace/obslab-predictive-kubernetes-scaling"
nav:
  - '1. About': index.md
  - '2. Getting Started': getting-started.md
  - '3. Cleanup': cleanup.md
#  - '4. Resources': resources.md
  - "4. What's Next?": whats-next.md
theme: material
